# Impostazioni SMTP per gmail
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true

# Credenziali per l'autenticazione SMTP di default
mail.username=gestionescadenze.app@gmail.com
mail.password=cmdq wolo ltir annm