# Impostazioni SMTP (esempio per Gmail)
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true

# --- CREDENZIALI DI DEFAULT (Hardcoded) ---
# Inserisci qui la mail e la password per app che vuoi usare per TUTTI
mail.username=gestionescadenze.app@gmail.com
mail.password=cmdq wolo ltir annm